stages:
- do_nothing

nothing:
  stage: do_nothing
  script: echo 'NOTHING'
  trigger:
    project: gcp-solutions/hcls/claims-modernization/gitlab-test-examples/deployapplications #use the specific branch to trigger
    branch: main
